### ISSUE TITLE
Building with runtime 20.08beta

### ISSUE THREAD

**Issue by adam-rich9929** [flathub/com.syntevo.SmartSynchronize#10]
It builds fine using runtime 19.08 and runs however it fails to build when runtime is changed to 20.08beta with the following error:
Error: module p7zip: Child process exited with code 2

**Comment by x80486** [comment]
I haven't tried `20.08` since it's in beta still; probably some dependencies changed and needs to be provided for `p7zip`, or the same should be updated.

**Comment by jakobjakobson13** [comment]
The patch in [https://github.com/flathub/org.gnome.FileRoller/pull/2](https://github.com/flathub/org.gnome.FileRoller/pull/2) could help.
