### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by strartem** [flathub/com.syntevo.SmartSynchronize#6]
Build and/or installation fails with "Error: Failed to install com.syntevo.SmartSynchronize: Wrong size for extra data https://www.syntevo.com/downloads/smartsynchronize/smartsynchronize-linux-4_0_1.tar.gz".

**Comment by x80486** [comment]
This is quite interesting; I could swear I grabbed the correct values for this one :astonished:

Both the checksum and size changed for this file – or I picked those two values wrongly the first time. Funny thing is, I know the `extra-data` size value is not checked at build time, but I do know the checksum is checked...so there is some witchery here I don't fully understand :man_shrugging:

In any case, this is fixed...we are back in business:

```shell
x80486@ubuntu-vm:~$ flatpak install --user https://dl.flathub.org/build-repo/6404/com.syntevo.SmartSynchronize.flatpakref

com.syntevo.SmartSynchronize permissions:
    ipc      wayland      x11      dri     file access [1]     dbus access [2]

    [1] host
    [2] org.freedesktop.Flatpak, org.freedesktop.Notifications


        ID                                   Arch           Branch         Remote                           Download
 1. [✓] com.syntevo.SmartSynchronize         x86_64         test           smartsynchronize1-origin         32.4 MB / 32.5 MB

Installation complete.
```

**Comment by strartem** [comment]
Great, thanks.
